# Data Wrangling

In [42]:
import pandas as pd

df = pd.read_csv('/content/cars sales.csv')

In [43]:
print(df.head())

         Car_id        Date Customer Name Gender  Annual Income  \
0  C_CND_000001  01-02-2022     Geraldine   Male          13500
1  C_CND_000002  01-02-2022           Gia   Male        1480000
2  C_CND_000003  01-02-2022        Gianna   Male        1035000
3  C_CND_000004  01-02-2022       Giselle   Male          13500
4  C_CND_000005  01-02-2022         Grace   Male        1465000

                           Dealer_Name   Company       Model  \
0  Buddy Storbeck's Diesel Service Inc      Ford  Expedition
1                     C & M Motors Inc     Dodge     Durango
2                          Capitol KIA  Cadillac    Eldorado
3               Chrysler of Tri-Cities    Toyota      Celica
4                    Chrysler Plymouth     Acura          TL

                      Engine Transmission       Color  Price ($)  Dealer_No   \
0  DoubleÂ Overhead Camshaft         Auto       Black      26000  06457-3834
1  DoubleÂ Overhead Camshaft         Auto       Black      19000  60504-7114
2          Overhead Camshaft       Manual         Red      31500  38701-8047
3          Overhead Camshaft       Manual  Pale White      14000  99301-3882
4  DoubleÂ Overhead Camshaft         Auto         Red      24500  53546-9427

  Body Style    Phone Dealer_Region
0        SUV  8264678    Middletown
1        SUV  6848189        Aurora
2  Passenger  7298798    Greenville
3        SUV  6257557         Pasco
4  Hatchback  7081483    Janesville

In [44]:
print(df.describe(include = 'all'))

              Car_id        Date Customer Name Gender  Annual Income  \
count          23906       23906         23905  23906   2.390600e+04
unique         23906         612          3021      2            NaN
top     C_CND_000001  09-05-2023        Thomas   Male            NaN
freq               1         190            92  18798            NaN
mean             NaN         NaN           NaN    NaN   8.308403e+05
std              NaN         NaN           NaN    NaN   7.200064e+05
min              NaN         NaN           NaN    NaN   1.008000e+04
25%              NaN         NaN           NaN    NaN   3.860000e+05
50%              NaN         NaN           NaN    NaN   7.350000e+05
75%              NaN         NaN           NaN    NaN   1.175750e+06
max              NaN         NaN           NaN    NaN   1.120000e+07

                                            Dealer_Name    Company     Model  \
count                                             23906      23906     23906
unique                                               28         30       154
top     Progressive Shippers Cooperative Association No  Chevrolet  Diamante
freq                                               1318       1819       418
mean                                                NaN        NaN       NaN
std                                                 NaN        NaN       NaN
min                                                 NaN        NaN       NaN
25%                                                 NaN        NaN       NaN
50%                                                 NaN        NaN       NaN
75%                                                 NaN        NaN       NaN
max                                                 NaN        NaN       NaN

                           Engine Transmission       Color     Price ($)  \
count                       23906        23906       23906  23906.000000
unique                          2            2           3           NaN
top     DoubleÂ Overhead Camshaft         Auto  Pale White           NaN
freq                        12571        12571       11256           NaN
mean                          NaN          NaN         NaN  28090.247846
std                           NaN          NaN         NaN  14788.687608
min                           NaN          NaN         NaN   1200.000000
25%                           NaN          NaN         NaN  18001.000000
50%                           NaN          NaN         NaN  23000.000000
75%                           NaN          NaN         NaN  34000.000000
max                           NaN          NaN         NaN  85800.000000

        Dealer_No  Body Style         Phone Dealer_Region
count        23906      23906  2.390600e+04         23906
unique           7          5           NaN             7
top     85257-3102        SUV           NaN        Austin
freq          3814       6374           NaN          4135
mean           NaN        NaN  7.497741e+06           NaN
std            NaN        NaN  8.674920e+05           NaN
min            NaN        NaN  6.000101e+06           NaN
25%            NaN        NaN  6.746495e+06           NaN
50%            NaN        NaN  7.496198e+06           NaN
75%            NaN        NaN  8.248146e+06           NaN
max            NaN        NaN  8.999579e+06           NaN

In [45]:
print(df.dtypes)

Car_id           object
Date             object
Customer Name    object
Gender           object
Annual Income     int64
Dealer_Name      object
Company          object
Model            object
Engine           object
Transmission     object
Color            object
Price ($)         int64
Dealer_No        object
Body Style       object
Phone             int64
Dealer_Region    object
dtype: object

## Handling Missing Values

In [46]:
print(df.isnull().sum())

Car_id           0
Date             0
Customer Name    1
Gender           0
Annual Income    0
Dealer_Name      0
Company          0
Model            0
Engine           0
Transmission     0
Color            0
Price ($)        0
Dealer_No        0
Body Style       0
Phone            0
Dealer_Region    0
dtype: int64

In [47]:
df.dropna(inplace = True)

In [48]:
print(df.isnull().sum())

Car_id           0
Date             0
Customer Name    0
Gender           0
Annual Income    0
Dealer_Name      0
Company          0
Model            0
Engine           0
Transmission     0
Color            0
Price ($)        0
Dealer_No        0
Body Style       0
Phone            0
Dealer_Region    0
dtype: int64

## Handle date column

In [49]:
from dateutil import parser

def parse_date(date_str):
  try:
    return parser.parse(date_str, dayfirst = True)
  except ValueError:
    return parser.parse(date_str)

df['Date'] = df['Date'].apply(parse_date)

In [50]:
df

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,C_CND_000001,2022-02-01,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÂ Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown
1,C_CND_000002,2022-02-01,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÂ Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora
2,C_CND_000003,2022-02-01,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville
3,C_CND_000004,2022-02-01,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco
4,C_CND_000005,2022-02-01,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÂ Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23901,C_CND_023902,2023-12-31,Martin,Male,13500,C & M Motors Inc,Plymouth,Voyager,Overhead Camshaft,Manual,Red,12000,60504-7114,Passenger,8583598,Pasco
23902,C_CND_023903,2023-12-31,Jimmy,Female,900000,Ryder Truck Rental and Leasing,Chevrolet,Prizm,DoubleÂ Overhead Camshaft,Auto,Black,16000,06457-3834,Hardtop,7914229,Middletown
23903,C_CND_023904,2023-12-31,Emma,Male,705000,Chrysler of Tri-Cities,BMW,328i,Overhead Camshaft,Manual,Red,21000,99301-3882,Sedan,7659127,Scottsdale
23904,C_CND_023905,2023-12-31,Victoire,Male,13500,Chrysler Plymouth,Chevrolet,Metro,DoubleÂ Overhead Camshaft,Auto,Black,31000,53546-9427,Passenger,6030764,Austin
23905,C_CND_023906,2023-12-31,Donovan,Male,1225000,Pars Auto Sales,Lexus,ES300,DoubleÂ Overhead Camshaft,Auto,Pale White,27500,38701-8047,Hardtop,7020564,Middletown

## Convert Data Types

In [51]:
df['Annual Income'] = pd.to_numeric(df['Annual Income'], errors = 'coerce')
df['Price ($)'] = pd.to_numeric(df['Price ($)'],errors = 'coerce')

In [52]:
df

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,C_CND_000001,2022-02-01,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÂ Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown
1,C_CND_000002,2022-02-01,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÂ Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora
2,C_CND_000003,2022-02-01,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville
3,C_CND_000004,2022-02-01,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco
4,C_CND_000005,2022-02-01,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÂ Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23901,C_CND_023902,2023-12-31,Martin,Male,13500,C & M Motors Inc,Plymouth,Voyager,Overhead Camshaft,Manual,Red,12000,60504-7114,Passenger,8583598,Pasco
23902,C_CND_023903,2023-12-31,Jimmy,Female,900000,Ryder Truck Rental and Leasing,Chevrolet,Prizm,DoubleÂ Overhead Camshaft,Auto,Black,16000,06457-3834,Hardtop,7914229,Middletown
23903,C_CND_023904,2023-12-31,Emma,Male,705000,Chrysler of Tri-Cities,BMW,328i,Overhead Camshaft,Manual,Red,21000,99301-3882,Sedan,7659127,Scottsdale
23904,C_CND_023905,2023-12-31,Victoire,Male,13500,Chrysler Plymouth,Chevrolet,Metro,DoubleÂ Overhead Camshaft,Auto,Black,31000,53546-9427,Passenger,6030764,Austin
23905,C_CND_023906,2023-12-31,Donovan,Male,1225000,Pars Auto Sales,Lexus,ES300,DoubleÂ Overhead Camshaft,Auto,Pale White,27500,38701-8047,Hardtop,7020564,Middletown

In [53]:
print(df.dtypes)

Car_id                   object
Date             datetime64[ns]
Customer Name            object
Gender                   object
Annual Income             int64
Dealer_Name              object
Company                  object
Model                    object
Engine                   object
Transmission             object
Color                    object
Price ($)                 int64
Dealer_No                object
Body Style               object
Phone                     int64
Dealer_Region            object
dtype: object

## Convert car id column

In [54]:
df['Car_id'] = df['Car_id'].str.extract('(\d+)$').astype(int)

In [55]:
print(df.head())

   Car_id       Date Customer Name Gender  Annual Income  \
0       1 2022-02-01     Geraldine   Male          13500
1       2 2022-02-01           Gia   Male        1480000
2       3 2022-02-01        Gianna   Male        1035000
3       4 2022-02-01       Giselle   Male          13500
4       5 2022-02-01         Grace   Male        1465000

                           Dealer_Name   Company       Model  \
0  Buddy Storbeck's Diesel Service Inc      Ford  Expedition
1                     C & M Motors Inc     Dodge     Durango
2                          Capitol KIA  Cadillac    Eldorado
3               Chrysler of Tri-Cities    Toyota      Celica
4                    Chrysler Plymouth     Acura          TL

                      Engine Transmission       Color  Price ($)  Dealer_No   \
0  DoubleÂ Overhead Camshaft         Auto       Black      26000  06457-3834
1  DoubleÂ Overhead Camshaft         Auto       Black      19000  60504-7114
2          Overhead Camshaft       Manual         Red      31500  38701-8047
3          Overhead Camshaft       Manual  Pale White      14000  99301-3882
4  DoubleÂ Overhead Camshaft         Auto         Red      24500  53546-9427

  Body Style    Phone Dealer_Region
0        SUV  8264678    Middletown
1        SUV  6848189        Aurora
2  Passenger  7298798    Greenville
3        SUV  6257557         Pasco
4  Hatchback  7081483    Janesville

In [56]:
df

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,1,2022-02-01,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÂ Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown
1,2,2022-02-01,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÂ Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora
2,3,2022-02-01,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville
3,4,2022-02-01,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco
4,5,2022-02-01,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÂ Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23901,23902,2023-12-31,Martin,Male,13500,C & M Motors Inc,Plymouth,Voyager,Overhead Camshaft,Manual,Red,12000,60504-7114,Passenger,8583598,Pasco
23902,23903,2023-12-31,Jimmy,Female,900000,Ryder Truck Rental and Leasing,Chevrolet,Prizm,DoubleÂ Overhead Camshaft,Auto,Black,16000,06457-3834,Hardtop,7914229,Middletown
23903,23904,2023-12-31,Emma,Male,705000,Chrysler of Tri-Cities,BMW,328i,Overhead Camshaft,Manual,Red,21000,99301-3882,Sedan,7659127,Scottsdale
23904,23905,2023-12-31,Victoire,Male,13500,Chrysler Plymouth,Chevrolet,Metro,DoubleÂ Overhead Camshaft,Auto,Black,31000,53546-9427,Passenger,6030764,Austin
23905,23906,2023-12-31,Donovan,Male,1225000,Pars Auto Sales,Lexus,ES300,DoubleÂ Overhead Camshaft,Auto,Pale White,27500,38701-8047,Hardtop,7020564,Middletown

## Remove Duplicates from data

In [57]:
df.drop_duplicates(inplace = True)

## Save cleaned sales data in 'Cleaned Car Sales'

In [58]:
df.to_csv('Cleaned Car Sales.csv', index=False)

## After this Analysis of data is done eith SQL and SSMS